# Generated by Django 6.0.1 on 2026-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="delivery_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
