# Generated by Django 6.0.1 on 2026-01-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
