# Generated by Django 6.0.1 on 2026-02-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_product_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="brand_logos/"),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
