# Generated by Django 6.0.1 on 2026-02-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_brand_description_brand_logo_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
