# Generated by Django 6.0.1 on 2026-02-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_updated_at_cart_user_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
    ]
